name: 'trino_utils_dbt_expectations_integration_tests'
version: '1.0'

profile: 'integration_tests'

config-version: 2

dispatch:
  - macro_namespace: dbt_utils
    search_order:
      [
        "trino_utils_dbt_expectations_integration_tests",
        "trino_utils",
        "dbt",
        "dbt_utils",
      ]
  - macro_namespace: dbt_date
    search_order:
      [
        "trino_utils_dbt_expectations_integration_tests",
        "trino_utils",
        "dbt",
        "dbt_date",
      ]
  - macro_namespace: dbt_expectations
    search_order:
      [
        "trino_utils_dbt_expectations_integration_tests",
        "trino_utils",
        "dbt",
        "dbt_expectations",
      ]

vars:
  'dbt_date:time_zone': 'America/Los_Angeles'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target", "dbt_modules", "dbt_packages"]

quoting:
    database: false
    identifier: false
    schema: false

models:
  dbt_expectations_integration_tests:
    +schema: dbt_expectations_integration_tests
    +materialized: table
  
